function story2 () {
    story.startCutscene(function () {
        scene.setBackgroundImage(img`
            fffffffffcccccccccc6666666666666666666666fff6666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffff666cccccccccccffffffffffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fff66666f66ffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666cccccccccccffffffffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fff666fff66ffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666cccccccccfffffffffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fff666fff66ffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666cccccccffffffffffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fff666fff66ffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666ccccfffffffffffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fff666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666cccccccccccccffffffffffffffffffffffffffffff
            fffffffffcccccccccc6666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666ccccccccccccccfffffffffffffffffffffffffffff
            fffffffffffcccccccc6666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666ccccccccccccccccffffffffffffffffffffffffffc
            fffffffffffcccccc666666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666ccccccccccccccccccccccccfffffffffffffffffff
            fffffffffffccccc6666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666666cccccccccccccccccccccccccffffffffffffffffff
            fffffffffffcccc66666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666cccccccccccccccccccccccccffffffffffffffffff
            fffffffffff66666666666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666ccccccccccccccccccccccccccfffffffffffffffffc
            fffffffffff66666666666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666ccccccccccccccc6cccccccccccffffffffffffffccc
            fffffffffff66666666666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666666666ccccccccccccffffffffffffcccc
            fffffffffff6666666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666666666ccccccccccccccffffffffcccccc
            ffffffffff6666666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666666666666666666cccccccccccccccffffffccccccc
            ffffffffff6666666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666666666666666666cccccccccccccccccffccccccccc
            ffffffffff666666666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666666666ccccccccccccccccccccccccccc
            fffffffffff6666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666666666666666cccccccccccccccccccccccccc
            fffffffffff666666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666666666666666ccccccccccccccccccccccccc
            ffffffffffff66666666666666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666666666cccccccccccccccccccccccc
            fffffffffffff666666666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666666666666cccccccccccccccccccccccc
            fffffffffffff66666666666666f66666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666666666666666ccccccccccccccccccccccc
            ffffffffffffff6666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666666666cccccccccccccc6ccccccc
            ffffffffffffff6666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666cccccc6666666ccccccc
            ffffffffffffff6666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66666666666666666666666666ccccccc
            ffffffffffffff6666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666666666666666ccccccc
            ffffffffffffff666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666666666666666ccccccc
            ffffffffffffff666666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffff6666666666666666ccccccc
            ffffffffffffff66666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffff6666666666666ccccccc
            ffffffffffffff6666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffbbbbbbffffffffffffffffffffffffffffffffffffffffffff6666666666666ccccccc
            ff666fffffffff6666666666fffffffffffffffffffffffffffffffffffffffffffffffffffbdbbbfffffffffffbbbbbffffffffffffffffffffffffffffffffffffffffffff6666666666666ccccccc
            66666666fffff6666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffbddbbbbbbffffffbbbbbbfffffffffffffffffffffffffffffffffffffffffff666666666666666cccc66
            6666666666fff6666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffbdddbccbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffff66666666666666
            66666666666f66666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddcccccbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffff666666666666
            66666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddcccccbbcccbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffff6666666666
            66666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdddccccccbcccbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfff66666
            66666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffccddccccccbcccbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccfffffff
            66666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccdccccccbcccbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccffffff
            ff666666666666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccbccccccbcccbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccfffff
            fffff66666666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccbccccccbcccbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccfffff
            fffffffc6666666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccbcccccccccccbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccfffff
            fffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccfffff
            fffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccffff
            fffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccffff
            fffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccfccccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccfff
            ffffffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfffccccbffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccfff
            ffffffcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfffccccbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccfff
            ffffffcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccffffccccbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccff
            ffffffcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccbdcccccccffffccccbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ffffffcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccddccccccffffffcccbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ffffffcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfffffffcbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ffffffcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccfffffcfccbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccfffffcfccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ffffffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccbbbbccccccffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            cfffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccbbbbccccccfffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ccffffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccbbbbccccccccfffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            ccffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccfffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffcccccccccc
            cccfffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccffffffffffffffffbbfffff777777777ffffffffffffffffffffffffffffffffcccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffffffffffff7777666777777777ffffffffffffffffffffffffffffffcccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccfffffcffffffffffffffffff7666666777777777fffffffffffffffffffffffffffffcccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffff66666cc66cccccccccffffffffffffffffffffffff7767766777777777fffffffffffffffffffffffffffffcccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffff667777cc6777777cccfffffffffffffffffffffffff76677777777777777ffffffffffffffffffffffffffffcccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff6666777776c6677777777777777bbbbfff77777777777766677777777777777ffffffffffffffffffffffffffffcccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff6777777776cc6777777777776676bbbddff7777776677776666777777777777ffffffffffffffffffffffffffffcccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffffffff67777777777767777777777776776bbdddff7777667777777676666666666677ffffffffffffffffffffffffffccccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffffff6677777777777776ff7777777f66776bbdddf777f777777777cccccccc6666667ffffffffffffffffffffffffffccccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffffff67777777777777cfccccccccffffffffbbddb77fff77777777ccbbbbbbccc666fffffffffffffffffffffffffffccccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffffff6776667777fffffccccccccccfffffffbbbbbbffffff777777ccbbbbbbbbbcccffffffffffffffffffffffffffcccccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffffff7766667ffffffffccccccccccccccccccffbbbbbfffffff7777fccbbbbbbbbbbbbffffffffffffffffffffffffffcccccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffffff77777777cffffffcccccccccccccccccccccbbbbbffffffffffffccbbbbbbbbbbbffffffffffffffffffffffffffccccccccccccc
            ccccccccffffffffffffffffffffffffffffffffffffffffffffff777777777ccccccccccccccccccccccccccccbbbbbccffffffffbbccbbbbbbbbbbbffffffffffffffffffffffffffccccccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffff7777777777ccccccccccccccccccccccccccccbdbbbcccccccccccbbcbbbbbbbbbbbffffffffffffffffffffffffffccccccccccccc
            ccccccccfffffffffffffffffffffffffffffffffffffffffffff7777777777ccccccccccccccccccccccccccccbdbbbccccccccccccbbccbbbbbbbbfffffffffffffffffffffffffffccccccccccccc
            ccccccccfffffffffffffffffff777777777777ffffffffffff777777777777ccccccccccccccccccccccccccccbbddcccccccccccccbbccbbbbbbbffffffffffffffffffffffffffffccccccccccccc
            ccccccccffffffffffffffffff77777777777777777777777777777777777777cccccccccccccccceeecccccccccbddccccccccccccccbccbbbbbbffffffffffffffffffffffffffffcccccccccccccc
            ccccccccfffffffffffffffff666777777777777777777777777777777777777cccccccccceddddddeeeccccccccbbbccccccccccccccbbcbbbbbfffffffffffffffffffffffffffffcccccccccccccc
            ccccccccfffffffffffffff66666777777777777777777777777777777777777ccccccccceedddddddeeecccccccbbbccccccccccccccbbcbbbbbffffffffffffffffffffffffffffccccccccccccccc
            ccccccccfffffffffffff66666667777777777777777777dddd7777777777777cccccccccebbddddddeeeeccccccbbcccccceeeeccccccbcbbbbfffffffffffffffffffffffffffffccccccccccccccc
            ccccccccffffffffffff6666666677777777777777777dddddd7777777777777ccccccbceebbddddddeeeeccccccbbcbbcceeeeeecccccbcbbbffffffffffffffffffffffffffffffccccccccccccccc
            ccccccccfffffffffff6666666667777777777777777dddddd77777777777777cccccbbcebbbddddddeeeecccccccbbbbcceeeeeecccccbcbbfffffffffffffffffffffffffffffffccccccccccccccc
            ccccccccffffffffff666666777777777777777777ddddddd777777777777777cccccbbcebbdddddddeeeecccccccbbbbcceeeeeeccccbbcbbffffffffffffffffffffffffffffffcccccccccccccccc
            ccccccccfffffffff6666666777777777777777777dddddd7777ddddd7777777ccccccccebddddddbdeeeeccccccccbbbccefeeffcccbbbcbbffffffffffffffffffffffffffffffcccccccccccccccc
            ccccccccfffffffff6666666677777777777777777777777777dddddd7777777ccccccccedddddddbdeeeecccccccbbbbccffeeefcccbcbcccffffffffffffffffffffffffffffffcccccccccccccccc
            ccccccccfffffff86666666666777777777777777777777777ddddd777777777ccccccccedddddddbdeeeeccccccdbcbbccfccccffcbbcbcccffffffffffffffffffffffffffffffcccccccccccccccc
            ccccccccff888888666666666666666666677777777777777777777777777777ccccccccedddddddbdeeeeccccccbccbbbcfcccccffbcccccfffffffffffffffffffffffffffffffcccccccccccccccc
            cccccc8c88ffffff666666666666666666677777777777777777777777777777ccccccccedddddddddeeeecccccbbcccbbcfccccccfbccccbbffffffffffffffffffffffffffffffcccccccccccccccc
            cccc888fffffffff666666666666666666667777777777777777777dddd77777ccccccccedddddddddeeeecccccbcccccbbfccccccfbccbccbbfffffffffffffffffffffffffffffcccccccccccccccc
            ccc88fffffffffff6666666666666666666667777777777777777dddddd77777ccccccccedddddddddeeeecccccbccccccbfccccccfbcbbbbbbddddfffffffffffffffffffffffffcccccccccccccbbb
            cc88ffffffffffffff6666666666666666666777777777777777777777777777ddddddddbbbbbbbbbbbbbbbdddbddddddddfddddddfddddddbbbddddfffffffffffffffffffffffddddddddddbbbbbbb
            888ffffffffffffffccccb66666666666666667777777777777777777ddd777ddddddddbbddbdddbbbddbbbbddddddddddddfddddddddddddbdbddddddddffffffffffffffddddddddddddddbbbbbbbb
            8ffffffffffffffffccccbbbb666666666666666777777777777777dddddddddddddddbbddbbdbdbbbbddbbbdddddddddddddddddddddddddddddddddddddddffffffffffdddddddddddddddbbbbbbbb
            fffffffffffffffffccccbbbbbbb666666666666677777777777777ddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbccc
            ffffffffffffffffcccccbbbbbbbbbbbb6666666666777777777777ddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbcccccc
            fffffffffffccccccccccbbbbbbbbbbbbbbdd666666667777777dddddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbdddddddddddddddddddddddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbcccccccc
            cccccccccccccccccccccbbbbbbbbbbdddddddddddddddddddddddddddddddddddddddddd1111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbcccccccccc
            cccccccccccccccccccccbbbbbbbbbddddddddddddddddddddddddddddddddddddddddddd11111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbccccccccccc
            cccccccccccccccccccbbbbbbbbbdddddddddddddddddddddddddddddddddddddddddddddd1111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbbcccccccccccc
            ccccccccccccccccbbbbbbbbbbbddddddddddddddddddddddddddddddddddddddddddddddd11111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbccccccccccccc
            ccccccccccccbbbbbbbbbbbbbbbdddddddddddddddddddddddddddddddddddddddddddddddd1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbcccccccccccccc
            ccccccccccccccbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddddd11111111111111ddddddd11111111111111ddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbccccccccccccccc
            ccccccccccccccbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddddddd111111111111dddddddd11111111111111ddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbccccccccccccccc
            ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddddd11dddd1ddd11dddddddd11111111111111dddddddddddddddddddddddddddddddddddddddddddddddddbbbbcccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbfffffdddddddddddddddddddddd1dddd1ddd1ddddddddd11111111111111ddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbccccccccccccccccc
            ccccccccccccccccccccccccccbbbbbfccccffffdddddddddddddddddd1dddd1ddd1ddddddddd11111111111111ddddddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbccccccccccccccccc
            ccccccccccccccccccccccccccbbbbbfccccccccffdddddddddddddddd1dddd1ddd1dddddddddd11111111111111ddddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbcccccccccccccccccc
            ccccccccccccccccccccccccccbbbbffcccccccccffddddddddddddddd1dddddbbd1dddddddddd11111111111111dddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbcccccccccccccccccc
            ccccccccccccccccccccccccccbbbbffffccccccccfddddddddddddddddddddbbbbdddddddddddd1111111111111dddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbbbbbccccccccccccccc
            ccccccccccccccccccccccccccbbbbbbffccccccccfdddddddddddddddddbbbbbbbddddddddddddd111111111111ddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbbcccccccccccccccccccc
            cccccccccccccccccccccccccbbbbbbbddccccccccfdddddddddddddbbbbbbbbbbbdddddddddddddd11111111111ddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbccccccccccccccccccccc
            ccccccccccccccccccccccccbbbbbbbbddddddccfffddddddddddbbbbbbbbbbbbbbdddddddddddddd11111111111ddddddddddddddddddddddddddddddddbbbbbbbbbbbbbbbccccccccccccccccccccc
            ccccccccccccccccccccccccbbbbbbbbbbdddddddddddddddbbbbbbbbbbbbbbbbbdddddddddddddddd1111111111dddddddbbbbbbbddddddddddddddddddbbbbbbbbbbbbbbbccccccccccccccccccccc
            ccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddd111111111dddddbbbbbbbbbbbbdddddddddddddddbbbbbbbbbbbbbbbccccccccccccccccccccc
            cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddddddddd1111111111dddbbbbbbbbbbbbbbbdddddddddddddbbbbbbbbbbbbbbbcccccccc111ccccccccccc
            ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddddddddddddddddddd1111111111ddbbbbbbbbbbbbbbbbbdddddddddddbbbbbbbbbbbbbbcccccccc11111ccccccccccc
            cccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111111111bbbbbbbbbbbbbbbbbbbbdddddddbbbbbbbbbbbbbbbccccccccc1111ccccccccccccc
            ccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111111111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc11111cccccccccccccc
            cccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111111111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc111ccccccccccccccccc
            ccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111111111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            `)
        dragon = sprites.create(img`
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            ....................................................................................................
            .................................................................................ffffffffffff.......
            ...............ffff............................................................ffaaaaaaaaaaaafff....
            ..........fffffaaaaffff.....................................................fffaaaaaa33333333333f...
            .......fffaaaaaaaaaaaaaff..................................................faaa33333333333333333f...
            ......faaa3333333333333aaf...fffff...............................fffff....faa333333333333333333fff..
            .....fa333333333333333333ffffaaaaaffffffff..................fffffaaaaaffffa3333333333333333ffff.....
            ....f33333333333333333333faaaaaaaaaaaaaaaaffffffffffffffffffaaaaaaaaaaaaaf3333333333333333f.........
            ....fff333b3333333333333faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf333333333b3fffff.........
            .......f333333333333333faaaaaaaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaf33333333ff..............
            ........fb3f3333b333333faaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaf3333333f................
            ........fff.ff3333333b3faaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaf3333333f................
            ..............f33333333faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf333333bf................
            ...............fffff3b3faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf3333333f................
            ...............ff...fbffaaaaaaaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaccccccaaaaaaff333333f................
            .....................fbffafaafcafaaaacaaaaaaaaaaaaaaaaaacaaaaacaaaafacfaafaff33333f.................
            ......................fffffffcfaafaaaaccaaccaaaaaaaaaaaaacaaccaaaafaafcfffff33333f..................
            .......................ffffffffffffffaacacaaaaaaaaaaaaaaaacacaafffffffffffff3333f...................
            .....................ffaf677777fff7ffffcaaaaaaaaaaaaaaaaaaaacffff7fff777776fff33f...................
            .....................faaff77777dff77777faaaaaaaaaaaaaaaaaaaaf77777dff77777ffafff....................
            .....................fafaf67777dff77777aaaaaaaaaaaaaaaaaaaaaa77777dff77776fafaaf....................
            ....................faaaacc6777fff7777aaaaaaaaaaaaaaaaaaaaaaaa7777fff7776ccaaaaf....................
            ....................faaaaacc677fff7aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa7fff776ccaaaaaf....................
            ...................faa3aaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaf....................
            ...................f3aaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaa3aaf...................
            ...................faaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaa3f...................
            ..................faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3aaaf...................
            ..................faaaa3aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf..................
            ..................fa3aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3aaf..................
            .................faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf..................
            .................faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3aaa3f..................
            .................fa3aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3aaf..................
            .................faa3a3aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf..................
            ..............fffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf...................
            ...........fffdddddfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3af...................
            ......fffffddddddddfa3aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf...................
            .....fddddddddffffffaaaaaaaaaaaaaaaaaafffffaaaaaaaaaaaaaaafffffaaaaaaaaaaaaaaaafdff.................
            ......ffffffff....ffaaaaaaaaaaaaaaaaafffffafaaaaaaaaaaaaafafffffaaaaaaaaaaaaaaafdddfff..............
            ................ffddfaaaaaaaaaaaaaaaaaaaaaaafaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaaafdddddddfff...........
            ...............fdddddfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffddddddddff.........
            ............fffddddddfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf...ffffddddddf........
            ..........ffddddddfffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffff...ffffdddf.......
            ........ffddddddff...fdfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffddddfff....fff........
            ......ffddddddff....fddfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafdddddddddfff............
            .....fdddddfff...fffdddffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffddddddddddff..........
            ......fffff.....fdddddddfffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffdffffffffddddddf.........
            ..............fffddddffff..ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff.fddddf.....fffffddf........
            ............ffdddddff........faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf....ffdddfff.......ff.........
            ...........fddddddff..........faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff......ffddddf.................
            ..........fdddddff.............faaaaaaaaaaaaaaa333a333aaaaaaaaaaaaafcf........ffdddf................
            .........fdddfff...............fabaaaaaaaaaaaa333333333aaaaaaaaaabafcf..........fdddf...............
            .........fdff..................ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccf...........ffddf..............
            ..........f....................fcfaaaaaaaaaaa33333333333aaaaaaaaafcccf.............ff...............
            ..............................fcccfaaaaaaaaaaaaaaaaaaaaaaaaaaaaafccccf..............................
            ..................ddd.........fccccfffaaaaaaaaaaaaaaaaaaaaaaafffcccccf..............................
            ..................d.dd........fcccccccfffaaaaaaaaaaaaaaaaafffcccccccccf.............................
            ..................d..ddd......fccccccccccfaaaaaaaaaaaaaaafccccccccccccf.............................
            ..................dddddd......fcccccccccccfffffffffffffffccccccccccccccf............................
            .........dddd................fcccccccccccccccccccccccccccccccccccccccccf............................
            .........ddddddd.............fccccccccccccccccccccccccccccccccccccccccccf...........................
            ......dddddddddd.............fccccccccccccccccccccccccccccccccccccccccccf...........................
            .......ddddddddd..........fffcccccdddccccccccccccccccccccccccccccccccccccf..........................
            ........dddddd...........fccccccccdcddddddccccccccccccccccccccccccccccccccf.........................
            ...........ddd...........fccccccccddcccccdcccccccccccccccccccccccccccccccccf........................
            .........................fccccccccccddddddccccccccccccccccccccccccccccccccccffff....................
            ........................fcccccccccccccccccccccccccccccccccccccccccccccccccccccccff..................
            .....................fffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccf..................
            ..................fffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccf.................
            `, SpriteKind.Player)
        donky_love_points = 0
        puss = sprites.create(img`
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ........................................fff.....................
            ......................................ff555f....................
            .....................................f554555f...................
            ............................fffffffff54454454f..................
            ...........................ffeeeeeeef45ff5554f..................
            ...........................ffffeeffffff.f4445f..................
            ..........................ffffffffeeeeef.ffff...................
            ......................ffffffffffffeeeeeff.......................
            .....................ffffef222222feeeefff.......................
            ....................ffffeef222222ffefffff.......................
            ....................ffeeeeefffffffffffff........................
            .....................ffeeeffffffffffffff........................
            ......................ffffffffffffff4f4f........................
            .......................fffffffff4f7df44f........................
            ........................fffffff444ff44f.........................
            .........................fffff44444444f.........................
            ..........................f444d33d4444f.........................
            ..........................f44bdbbdb444f.........................
            ..........................ff4ddbbdd44f..........................
            ..........................fff4bddb44f...........................
            ..........................fefffddfffff..........................
            .........................ffef44ff44feef.........................
            ........................f44feff44ffeefff........................
            ........................f444feeffeeff444f.......................
            .......................f44444fedeef444444f......................
            .......................f444444ffff4444444f......................
            .......................f44f4455dd5444f444f......................
            .......................f44f44d5dd5544f444f......................
            .......................f44f4dddddddd4f444f......................
            .......................f44f44ddddddd44f44f......................
            .......................f44f44dddddd444f44f......................
            .......................f44f44dddddd444f44f......................
            .......................f44f45dddddd544f44f......................
            .......................f44f4dddddddd44f44f......................
            .......................f44f445dddd5444f44f......................
            .......................ffff44dddddd544f4fef.....................
            .......................feefff4ddddd544fffef.....................
            .......................fbefeeffffdd54f555f......................
            ........................fbfee5ed5ffff55bb5f.....................
            .........................fffe5de5eeef5ddd5f.....................
            .........................f44fffffeeef55d55f.....................
            .........................f444ddddfffff555f......................
            .........................f4444ddddd544fff.......................
            .........................f44445ddddd44f.........................
            .........................f44444ddd5444f.........................
            ..........................f44444444444f.........................
            ..........................f44444444444f.........................
            ..........................fffff444fffff.........................
            ..........................fffeffffffeff.........................
            ..........................ffeeff.feeeff.........................
            ..........................fffeef.ffeeff.........................
            ...........................feeef.fffeff.........................
            ..........................ffeef...ffeef.........................
            ..........................feeff...ffeef.........................
            ..........................fffef..fffeef.........................
            .........................fffeef..ffffeff........................
            ........................ffeefff..ffffeeef.......................
            ........................ffffff....fffffef.......................
            ........................fffff.......fffff.......................
            ................................................................
            `, SpriteKind.Player)
        srhek = sprites.create(img`
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ....................ffff...............ffff.....................
            ...................f775f...............f577f....................
            ...................f76f7f..fffffffff..f7f67f....................
            ....................ff77fff777767777fff77ff.....................
            ......................f77777677776777777f.......................
            .......................f777777777777777f........................
            .......................f77ee7777777ee77f........................
            ......................f77e77ee777ee77e77f.......................
            ......................f777fff77777fff777f.......................
            ......................f77f1e1f777f1e1f77f.......................
            ......................f777fff77777fff777f.......................
            ......................f77777777777777777f.......................
            ......................f77777767776777777f.......................
            ......................f77777677777677777f.......................
            ......................f77777766666777777f.......................
            ......................f77767777777776777f.......................
            .......................f763777777777367f........................
            .......................f777333333333777f........................
            ........................f7777777777777f.........................
            .......................feff777777777ffef........................
            ....................fffeefffffffffffffeefff.....................
            ...................fdddfeeffdddddddffeefdddf....................
            ...................fdddffeefdddddddfeeffdddf....................
            ...................fdddffeeefdddddfeeeffdddf....................
            ..................fdddbfefefffdddfffefefbdddf...................
            ..................fdddfefefffdefedfffefefdddf...................
            ..................fdddffefeffdfdfdffefeffdddf...................
            ..................fdddfffefffdddddfffefffdddf...................
            ..................fdddffefeffdddddffefeffdddf...................
            ..................fddbfffffffdddddfffffffdddf...................
            ..................fddbffffeffdddddffeffffdddf...................
            ..................fdddfffffffdddddfffffffdddf...................
            ..................fdddbbdddddddddddddddbbdddf...................
            ..................ffffbdddddddddddddddddbffff...................
            ..................f677fdddddddddddddddddf776f...................
            ..................f677eedddddddddddddddfe776f...................
            ...................f67fbeeedddddddddeffdf76f....................
            ....................ffbbbbbeeeeeeeeedddddff.....................
            .....................ffbbdddddddddddddbbff......................
            .....................feffbbbbbbbbbbbbbffef......................
            .....................feeefffffffffffffeeef......................
            ......................feeeeeef...feeeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            ......................feeeeef.....feeeeef.......................
            .......................feeeef.....feeeef........................
            .......................feeeef.....feeeef........................
            .......................ffffff.....ffffff........................
            ......................fcccccf.....fcccccf.......................
            .....................ffffffff.....ffffffff......................
            .....................fffffff.......fffffff......................
            ................................................................
            ................................................................
            `, SpriteKind.Player)
        sudecs = 0
        srhek.setPosition(120, 70)
        puss.setPosition(180, 160)
        dragon.setPosition(180, 160)
        story.printText("Shrek:yeh she looked pretty good ig.", 75, 100)
        story.printText("(phone rings)", 75, 100)
        story.printText("Shrek: yeh ok ill be there cya babe.", 75, 100)
        story.printText("(hangs up)", 75, 100)
        story.printText("Shrek: sorry broskie i gotta go home to fiona! Wifes am i right", 75, 100)
        srhek.setPosition(180, 160)
        story.printText("You: shit he left again ..,", 75, 100)
        story.printText("You: i dont know why im so upset ..,", 75, 100)
        story.printText("You: do i.., love him??", 75, 100)
        story.printText("TITLE SCEEN", 75, 75)
        far = sprites.create(img`
            ................................................................
            ................................................................
            ................................................................
            ........................fffffffffffffff.........................
            .......................f555555555555555f........................
            ......................f52222222222222225f.......................
            .....................f5222222222222222225f......................
            .....................f2222222222222222222f......................
            .....................f2222222222222222222f......................
            .....................f2252525252525252522f......................
            ......................f22222222222222222f.......................
            .......................f555555555555555f........................
            ........................fffffffffffffff.........................
            .......................ffdccccdddccccdff........................
            .......................ffddfffcdcfffddff........................
            .......................ffdf191fdf191fdff........................
            .......................ffddfffdbdfffddff........................
            .......................ffddddddbddddddff........................
            ......................fffdddddddddddddfff.......................
            ......................fffdddddfdfdddddfff.......................
            ......................fffdddbdddddbdddfff.......................
            .....................ffffddb3deded3bddffff......................
            .....................ffffdddd33333ddddffff......................
            .....................fcffdedddddddddedffcf......................
            ......................fcffddeddeddeddffcf.......................
            .......................fcfdddddddddddfcf........................
            ........................ffffddededdffff.........................
            ...........................fffffffff............................
            ...........................fbbbbbbbf............................
            ...........................fdddddddf............................
            .......................ffff2fdddddf2ffff........................
            ...................ffff2225d2fffff2d5222ffff....................
            ..................f222222225d22222d522222222f...................
            .................f222222222255555552222222222f..................
            .................fd2222f222222555222222f2222df..................
            ................fdd22d2f222222252222222f2d22ddf.................
            ................f2d2dd2f222222222222222f2dd2d2f.................
            ................f222dd2f222222222222222f2dd222f.................
            .................f222d2f222222222222222f2d222f..................
            ..................f2222f2222222222222222f222f...................
            ...................ffff22222222222222222ffff....................
            ...................ffff22222222222222222ffff....................
            ...................ffff22222222222222222ffff....................
            ....................fff22222222222222222fff.....................
            ....................fff22222222222222222fff.....................
            ....................fff22222222222222222fff.....................
            ....................ffff222222222222222ffff.....................
            ....................f22f222222222222222f22f.....................
            ....................f555ffffffcfcffffff555f.....................
            ....................f22fbbbff5cfc5ffbbbf22f.....................
            ....................f22f222222222222222f22f.....................
            .....................f2f222222222222222f2f......................
            ......................ff2222222222222222f.......................
            ......................f22222222222222222f.......................
            ......................f22222222222222222f.......................
            ......................fffffffffffffffffff.......................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            ................................................................
            `, SpriteKind.Player)
        far.setPosition(120, 70)
        story.printText("You: farquad oh what should i do?!", 75, 100)
        story.printText("You:...", 75, 100)
        story.printText("You: yes?", 75, 100)
        story.printText("Farquad: fuck him.", 75, 100)
        story.printText("You: what a great idea! Then we can get married have fun oh my i must go home!", 75, 100)
        story.printText("Farquad: thats not what i mea-", 75, 100)
        far.setPosition(180, 160)
        story.printText("You: what a great idea!", 75, 100)
        story.printText("You: oof!", 75, 100)
        donk = sprites.create(img`
            ................................................................
            ................................................................
            ................................................................
            .....................fff........................................
            ....................ffccf............ffff.......................
            ....................fcffcf.........ffcccf.......................
            .....................fcbfcf.f..f..fccfbcf.......................
            ......................fcbfcffff..fcfbbcf........................
            .......................fcbfcffcffcfbbcf.........................
            ........................fcbbfcffbbbcff..........................
            .........................fbfffcffbcf............................
            ..........................fffffffff.............................
            ..........................fbbbfbbbbf............................
            .........................fbcccbcccbbf...........................
            .........................fcffbbbffcbf...........................
            .........................ff1efbf1efbf...........................
            .........................fbffbbbffbbf...........................
            .........................fbbbbbbbbbbf...........................
            .........................fbdddddbbbbf...........................
            ........................fbdddddcdbbbf...........................
            ........................fddddddccdbbbf..........................
            .......................fddddddddddbbbbf.........................
            .......................fddddddddd3dbbbf.........................
            .......................fdddddddd33dbbbf.........................
            ........................f333333313dbbbf.........................
            ........................fd1d11d1b3dbbbf.........................
            .........................fdbd1bdf3dbbf..........................
            .........................fffffff3dbbf...........................
            .........................f3b11d3dbbf............................
            ..........................f3333dbbbf............................
            ..........................fdddddbbbf............................
            ..........................fdddddbbbf............................
            .........................fdddddddbbbf...........................
            ........................fdddddddbbbbbf..........................
            .......................fddddddddbbbbbbf.........................
            .......................fdddddddcbbbbbbf.........................
            ......................fbdddddddcbbbbbbf.........................
            .....................fdbddddddbbbbbbbbf.........................
            .....................fddddddddbbbbbbbbf.........................
            .....................fddddddddbbbbbbbbf.........................
            .....................fddddddddcbbbbbbbf.........................
            .....................fddddddddcbbbbbbf..........................
            .....................fcdbdddddcbbbbbccf.ff......................
            .....................fccbdddddccbbbcbcf.fff.....................
            ......................fbcbdddddcbbbcbbffcf......................
            ......................fbcfdddddcbbbcbbbfccf.....................
            ......................fbcfddddccbbcbbbbbfcf.....................
            ......................fbbcfdddcbbbcbbbbbfcf.....................
            ......................fbbbccddcbbcbbbbbbff......................
            ......................fbbbbbccbbbcbbbbbbf.......................
            .....................ffbbbbcccbbccbbbbbbf.......................
            ...................ffffbbbbbcbbbfbcbbbbbff......................
            ...................feffbbbbbfbbfbbccbbbffff.....................
            ...................feeffbbbfbbbcbbbbbbffffef....................
            ....................ff..ffbfbbbfcccbbff.fef.....................
            ..........................ffbbfffffff....f......................
            ...........................fbbffef..............................
            ...........................feffff...............................
            ..........................ffeef.................................
            .........................ffffff.................................
            .........................fffff..................................
            ................................................................
            ................................................................
            ................................................................
            `, SpriteKind.Player)
        donk.setPosition(120, 70)
        story.printText("Donkey: hi im donkey! And you are?", 75, 100)
        story.printText("You: hi donkey im!", 75, 100)
        story.printText(game.askForString(""), 75, 100)
        story.printText("Donkey: sorry im in such a rush! Im going off to see shrek! Do you know him? Hes the best!", 75, 100)
        story.showPlayerChoices("Yes of course i know him!", "I just came from his house!")
        if (story.getLastAnswer() == "Yes of course i know him!") {
            story.printText("You:Yes of course i know him!", 75, 100)
        } else {
            story.printText("You:I just came from his house!", 75, 100)
        }
        story.printText("Donkey: thats so cool! I havennt seen shrek in a while so im very exited!", 75, 100)
        story.printText("You: cool.", 75, 100)
        story.printText("Donkey: hey quickly, dragon is off with the kids and i have no ride can you drive me?", 75, 100)
        story.showPlayerChoices("of course!", "i would rather not...")
        if (story.getLastAnswer() == "of course!") {
            story.printText("you: of course!", 75, 100)
            donky_love_points += 1
            story.printText("donkeys love points changed by 1", 75, 100)
        } else {
            story.printText("you: i would rather not...", 75, 100)
        }
        story.printText("Donkey: ( jumps into car) awesome! Lets go!", 75, 100)
        story.printText("(now in car)", 75, 100)
        story.printText("Donkey: so what do you do for a living?", 75, 100)
        story.printText("i work as a" + game.askForString(""), 75, 100)
        story.printText("Donkey: thats so cool !", 75, 100)
        story.printText("You: cool.", 75, 100)
        story.printText("Donkey: Hey can you turn here? I think it should be faster.", 75, 100)
        story.showPlayerChoices("Yes.", "No.")
        if (story.getLastAnswer() == "Yes.") {
            story.printText("you: Yes.", 75, 100)
            story.printText("Donkey: cool awesome!", 75, 100)
            story.printText("/5 minutes later/ ", 75, 100)
            story.printText("Donkey: sorry! I didn't think we would get stuck in traffic i really thought it would be faster!", 75, 100)
            story.showPlayerChoices("Its ok dont worry", "Goddam.")
            if (story.getLastAnswer() == "Its ok dont worry") {
                story.printText("Its ok dont worry", 75, 100)
                story.printText("Donkey: so how do you know shrek?", 75, 100)
                story.printText("You: we used to go bowling together, he was so sweet to me! But i had to quit the club so we just meet once a week.", 75, 100)
                story.printText("Donkey: thats so cool! Hey you can pull over here!", 75, 100)
                story.printText("You: ok!", 75, 100)
                story.printText("(pulls over) (out of car)", 75, 100)
            } else {
                story.printText("Goddam.", 75, 100)
                story.printText("Donkey: so how do you know shrek?", 75, 100)
                story.printText("You: we used to go bowling together, he was so sweet to me! But i had to quit the club so we just meet once a week.", 75, 100)
                story.printText("Donkey: thats so cool! Hey you can pull over here!", 75, 100)
                story.printText("You: ok!", 75, 100)
                story.printText("(pulls over) (out of car)", 75, 100)
            }
        } else {
            story.printText("you: No.", 75, 100)
            story.printText("donkey: oh, ok i quess", 75, 100)
            story.printText("Donkey: so how do you know shrek?", 75, 100)
            story.printText("You: we used to go bowling together, he was so sweet to me! But i had to quit the club so we just meet once a week.", 75, 100)
            story.printText("Donkey: thats so cool! Hey you can pull over here!", 75, 100)
            story.printText("You: ok!", 75, 100)
            story.printText("(pulls over) (out of car)", 75, 100)
            story.printText("Donkey: you know you really should of gone with my route before.", 75, 100)
            story.showPlayerChoices("Its ok dont worry", "Goddam.")
        }
        if (donky_love_points == 1) {
            story.printText("Donkey: hey quickly, before i go in let me teach you a little trick to get the one you want! If you wanna be charismatic like me remember to press B.", 75, 100)
            story.printText("You: thankyou!", 75, 100)
            story.printText("Donkey: well ill see you sometime! bye!", 75, 100)
            sudecs += 1
        } else {
            story.printText("Donkey: you really wernt that nice to me today! ", 75, 100)
            story.printText("Donkey: im gonna tell shrek all about this!", 75, 100)
            donky_love_points += -1
        }
        donk.setPosition(180, 160)
        puss.setPosition(120, 70)
    })
}
let donk: Sprite = null
let far: Sprite = null
let sudecs = 0
let srhek: Sprite = null
let puss: Sprite = null
let donky_love_points = 0
let dragon: Sprite = null
story2()
